"""
provision.py — Wajntraub demo device provisioning state machine.

Sequences:
  INIT → AP_MODE → PROVISIONED → CONNECTING → ONLINE
  CONNECTING → ERROR → AP_MODE  (one retry on nmcli failure)
  AP_MODE    → ERROR            (timeout — default 10 min)

Run as root:
  sudo python3 device/provision.py

Environment variables:
  PROVISION_IFACE   Wi-Fi interface for SoftAP (auto-detected via `iw dev` if unset)
  PROVISION_TIMEOUT AP_MODE timeout in seconds (default: 600)
"""

import enum
import logging
import os
import ssl
import subprocess
import threading

import server
import wifi

log = logging.getLogger(__name__)

TIMEOUT = int(os.environ.get('PROVISION_TIMEOUT', '600'))

_CERT_PATH = os.path.join(os.path.dirname(__file__), '..', 'certs', 'device.crt')
_KEY_PATH  = os.path.join(os.path.dirname(__file__), '..', 'certs', 'device.key')


# ---------------------------------------------------------------------------
# State enum
# ---------------------------------------------------------------------------

class ProvisionState(enum.Enum):
    INIT        = 'INIT'
    AP_MODE     = 'AP_MODE'
    PROVISIONED = 'PROVISIONED'
    CONNECTING  = 'CONNECTING'
    ONLINE      = 'ONLINE'
    ERROR       = 'ERROR'


# ---------------------------------------------------------------------------
# Internal helpers (patchable in unit tests)
# ---------------------------------------------------------------------------

def _load_ssl_context(cert_path=_CERT_PATH, key_path=_KEY_PATH):
    """
    Load ssl.SSLContext for the HTTPS provisioning server.

    Uses a software RSA key generated by setup.sh. Python's ssl module calls
    SSL_CTX_use_PrivateKey_file() which uses fopen() and cannot resolve TPM
    store URIs like "handle:0x81000001". The tpm2-openssl provider hooks into
    OpenSSL's OSSL_STORE API, which Python stdlib ssl never invokes.

    Production path: tpm2-pkcs11 exposes the TPM key via PKCS#11; OpenSSL's
    PKCS#11 engine/provider IS reachable from Python ssl, keeping the private
    key hardware-backed. Out of scope for this demo.

    In unit tests, patch 'provision._load_ssl_context' to avoid needing real
    cert files. The patch target is the helper, not ssl.SSLContext directly.
    """
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(cert_path, keyfile=key_path)
    return ctx


def _detect_wifi_iface() -> str:
    """Return the first wireless interface found by iw, or 'wlan0' as fallback.

    Falls back to 'wlan0' if iw is not installed or returns no interfaces.
    Override with PROVISION_IFACE to skip auto-detection entirely.
    """
    try:
        result = subprocess.run(['iw', 'dev'], capture_output=True, text=True)
    except FileNotFoundError:
        log.warning('iw not found — falling back to wlan0. Install iw or set PROVISION_IFACE.')
        return 'wlan0'
    for line in result.stdout.splitlines():
        line = line.strip()
        if line.startswith('Interface '):
            return line.split()[1]
    return 'wlan0'


def _log_transition(from_state: ProvisionState, to_state: ProvisionState) -> None:
    log.info('State: %s → %s', from_state.value, to_state.value)


# ---------------------------------------------------------------------------
# State machine
# ---------------------------------------------------------------------------

def run(iface: str = None) -> None:
    """
    Run the provisioning state machine.

    Parameters
    ----------
    iface : Wi-Fi interface for SoftAP. Reads PROVISION_IFACE env var if None.
            Defaults to 'wlan0'.
    """
    if iface is None:
        iface = os.environ.get('PROVISION_IFACE') or _detect_wifi_iface()

    state      = ProvisionState.INIT
    ssl_ctx    = None
    credentials: dict = {}
    result: dict = {}
    result_event = threading.Event()
    srv    = None
    thread = None
    retry_count = 0
    MAX_RETRIES = 1

    log.info('State: %s', state.value)

    while True:

        # -------------------------------------------------------------------
        if state == ProvisionState.INIT:
            try:
                ssl_ctx = _load_ssl_context()
                _log_transition(state, ProvisionState.AP_MODE)
                state = ProvisionState.AP_MODE
            except Exception as exc:
                log.error('INIT failed: %s', exc, exc_info=True)
                state = ProvisionState.ERROR

        # -------------------------------------------------------------------
        elif state == ProvisionState.AP_MODE:
            credentials = {}
            result = {}
            result_event = threading.Event()
            event = threading.Event()

            try:
                wifi.start_ap(iface)
                srv, thread = server.create_server(
                    credentials, event, ssl_ctx,
                    result=result, result_event=result_event,
                )
            except Exception as exc:
                log.error('AP_MODE start failed: %s', exc)
                state = ProvisionState.ERROR
                continue

            fired = event.wait(timeout=TIMEOUT)

            if not fired:
                log.error('AP_MODE timed out after %ds', TIMEOUT)
                srv.shutdown()
                thread.join()
                wifi.stop_ap()
                _log_transition(state, ProvisionState.ERROR)
                state = ProvisionState.ERROR
            else:
                # Do NOT join here — server thread is blocked in POST handler
                # waiting on result_event, which the CONNECTING state sets.
                # Joining here would deadlock.
                _log_transition(state, ProvisionState.PROVISIONED)
                state = ProvisionState.PROVISIONED

        # -------------------------------------------------------------------
        elif state == ProvisionState.PROVISIONED:
            _log_transition(state, ProvisionState.CONNECTING)
            state = ProvisionState.CONNECTING

        # -------------------------------------------------------------------
        elif state == ProvisionState.CONNECTING:
            try:
                wifi.connect(credentials['ssid'], credentials['password'])
                result['ok'] = True
                result_event.set()
                thread.join(timeout=5)  # server responds with success, shuts itself down
                _log_transition(state, ProvisionState.ONLINE)
                state = ProvisionState.ONLINE
            except wifi.WifiConnectError as exc:
                log.error('nmcli connect failed: %s', exc)
                result['ok'] = False
                result['reason'] = exc.user_message
                result_event.set()
                srv.shutdown()   # failure path skips shutdown_callback — free port 443 manually
                thread.join(timeout=5)
                _log_transition(state, ProvisionState.ERROR)
                state = ProvisionState.ERROR

        # -------------------------------------------------------------------
        elif state == ProvisionState.ONLINE:
            log.info('Provisioning complete — device is connected.')
            return

        # -------------------------------------------------------------------
        elif state == ProvisionState.ERROR:
            if retry_count < MAX_RETRIES:
                retry_count += 1
                log.info('Retrying AP_MODE (attempt %d/%d)', retry_count, MAX_RETRIES)
                _log_transition(state, ProvisionState.AP_MODE)
                state = ProvisionState.AP_MODE
            else:
                log.error('Provisioning failed after %d retries — giving up.', MAX_RETRIES)
                return


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s %(levelname)s %(message)s',
    )
    run()
